! This hub-height wind-speed file was generated by FLAggTurb on 27-May-2024 at 10:23:40.
!
! The requested statistics for this data were:
!    Mean Total Wind Speed =   10.000 m/s
!    Turbulence Intensity  =    8.966%
!
!       Time          HorSpd           WndDir          VerSpd         HorShr          VerShr          LnVShr          GstSpd          Upflow
!      (sec)          (m/s)            (deg)           (m/s)           (-)             (-)             (-)            (m/s)            (deg)
    0.000000E+00    0.800000E+01    0.000000E+00    0.000000E+00    0.000000E+00    0.140000E+00    0.000000E+00    0.000000E+00    0.000000E+00
    0.119990E+03    0.800000E+01    0.000000E+00    0.000000E+00    0.000000E+00    0.140000E+00    0.000000E+00    0.000000E+00    0.000000E+00
    0.120000E+03    0.900000E+01    0.000000E+00    0.000000E+00    0.000000E+00    0.140000E+00    0.000000E+00    0.000000E+00    0.000000E+00
    0.240000E+03    0.900000E+01    0.000000E+00    0.000000E+00    0.000000E+00    0.140000E+00    0.000000E+00    0.000000E+00    0.000000E+00
